version: 2

jobs:
  build:
    working_directory: ~/django-google-sheets-export
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: py-deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run Static Analysis
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            cd django_google_sheets_export && python manage.py test && cd ..
